## Service definition ##
application:
  schemaVersion: 1.0.0-preview2
  name: Basta2019Mesh
  properties:
    services:
      - name: Order
        properties:
          description: Order description.
          osType: Windows
          codePackages:
            - name: Order
              image: order:dev
              endpoints:
                - name: OrderListener
                  port: 80
              environmentVariables:
                - name: deliveryservicename
                  value: "[parameters('OrderService_DeliveryServiceName')]"
              resources:
                requests:
                  cpu: "[parameters('Order_cpu')]"
                  memoryInGB: 1
          replicaCount: 1
          autoScalingPolicies:
            - name: AutoScaleWorkerRule
              trigger:
                kind: AverageLoad
                metric:
                  kind: Resource
                  name: cpu
                lowerLoadThreshold: 0.2
                upperLoadThreshold: 0.8
                scaleIntervalInSeconds: 60
              mechanism:
                kind: AddRemoveReplica
                minCount: 1
                maxCount: 5
                scaleIncrement: 1
          networkRefs:
            - name: Basta2019MeshNetwork
              endpointRefs:
                - name: OrderListener
